required:
- id
- name
- brand

optional:
- category_id
- created_at
- updated_at
- description
- model
- unit
- average_rating
- is_active
- is_featured
- price

disallowed:
- legacy_code
- temp_flag
